language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8
      - python

before_script:
      - mkdir build && cd build && cmake ..

before_install:
      - gem install coveralls-lcov
install:
      - export CXX="g++-4.8"

script: make

after_success:
  - ls
  - mkdir gt_test
  - git clone --branch dev https://github.com/caymard/SfM_quality_evaluation.git gt_test/
  - cd gt_test
  - echo "../`uname -s`-`uname -p`-Release"