language: cpp

compiler: gcc

branch: dev

before_install:
- sudo apt-get update
- sudo add-apt-repository ppa:apokluda/boost1.53 -y

install:
- sudo apt-get install libeigen3-dev
- sudo apt-get install libboost-filesystem1.53-dev -y
- sudo apt-get install libboost-program-options1.53-dev -y
- sudo apt-get install libboost-test1.53-dev -y

before_script: mkdir build && cd build && cmake ..

script: make
