language: cpp

compiler: gcc

before_install:
- sudo add-apt-repository ppa:apokluda/boost1.53 -y
- sudo apt-get update

install:
- sudo apt-get install libeigen3-dev
- sudo apt-get install libboost1.53-dev
- sudo apt-get install libboost-filesystem1.53-dev

before_script: mkdir build && cd build && cmake ..

script: make
