language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff-dev
      - libxxf86vm1
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8

before_script:
      - mkdir build && cd build && cmake ..

script: make
