language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8
      - python

env:
  global:
    - OPENCV_ROOT=${TRAVIS_BUILD_DIR}/opencv3
    - OPENCV_SOURCE=${OPENCV_ROOT}/source
    - OPENCV_BUILD=${OPENCV_ROOT}/build
    - OPENCV_INSTALL=${OPENCV_ROOT}/install

before_install:
      - mkdir --parent ${OPENCV_SOURCE}
      - mkdir --parent ${OPENCV_BUILD}
      - mkdir --parent ${OPENCV_INSTALL}
      - git clone --recursive --branch 3.0.0 https://github.com/Itseez/opencv.git ${OPENCV_SOURCE}
      - cd ${OPENCV_BUILD}
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${OPENCV_INSTALL} ${OPENCV_SOURCE}
      - make -j 16
      - make install
install:
      - export CXX="g++-4.8"

before_script:
      - cd ${TRAVIS_BUILD_DIR} & ls -l
      - mkdir build && cd build
      - ls -l
      - cmake /home/travis/build/caymard/sandtracer

script: make -j 2

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/opencv3/install