language: cpp
compiler: gcc
before_install:
- sudo apt-get update
- sudo apt-get install libboost1.55-dev
install: sudo apt-get install libeigen3-dev
before_script: mkdir build && cd build && cmake ..
script: make
