language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8
      - python

before_install:
      - gem install coveralls-lcov
      - cd /home/travis/build
      - mkdir opencv3 && cd opencv3 && ls -l
      - git clone --recursive --branch 3.0.0 https://github.com/Itseez/opencv.git source
      - mkdir install && mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/travis/build/opencv3/install ../source
      - make -j 16
      - make install
install:
      - export CXX="g++-4.8"

before_script:
      - cd /home/travis/build/caymard & ls -l
      - mkdir build && cd build
      - ls -l
      - cmake /home/travis/build/caymard/sandtracer

script: make -j 2

cache:
  directories:
    - opencv3