language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
  apt:
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev

before_script: mkdir build && cd build && cmake ..

script: make
