language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
	apt:
		packages:
			- cmake
			- libboost1.53-all-dev
			- libeigen3-dev

before_script: mkdir build && cd build && cmake ..

script: make
