language: cpp

compiler: gcc

branch: dev

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8
      - python

before_script:
      - cd .. & mkdir build && cd build && cmake ../sandtracer

before_install:
      - gem install coveralls-lcov
      - git clone --recursive --branch 3.0.0 https://github.com/Itseez/opencv.git opencv3_source
      - mkdir opencv3_build
      - mkdir opencv3_install
      - cd opencv3_build
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/travis/build/caymard/opencv3_install ..
      - make -j 2
      - make install
      - cd ..
install:
      - export CXX="g++-4.8"

script: make

after_success:
  - ls
  - mkdir gt_test
  - git clone --branch dev https://github.com/caymard/SfM_quality_evaluation.git gt_test/
  - cd gt_test
  - echo "../`uname -s`-`uname -p`-Release"